'$schema' = 'https://starship.rs/config-schema.json'

palette             = 'tokyo-night-neon'
add_newline         = true
command_timeout     = 1000
continuation_prompt = '[❯❯ ](dimmed white-fg)'

# https://www.nerdfonts.com/cheat-sheet
#      

format = """\
[](power-1-bg)\
$time\
[](bg:power-2-bg fg:power-1-bg)\
$directory\
[](bg:power-3-bg fg:power-2-bg)\
$git_branch\
[](bg:power-4-bg fg:power-3-bg)\
$git_commit\
[](fg:power-4-bg)\
$fill\
$git_state\
$git_status\
$git_metrics\
$cmd_duration\
$line_break\
${custom.rbenv}${custom.nodenv}\n$character"""

[character]
disabled       = false
success_symbol = '[❯](bold fg:green)'
error_symbol   = '[❯](bold fg:red)'
vimcmd_symbol  = '[❮](bold fg:green)'

[cmd_duration]
format   = '[  󰅒 $duration ](italic white-fg)'
min_time = 2_000

[custom.nodenv]
disabled = false
style    = 'fg:white-2-fg'
format   = "[ ([$symbol](green-fg)$output) ]($style)"
command  = 'zsh ~/dotfiles/zsh/node-version.zsh'
symbol   = ' ' # https://unicode-explorer.com/c/202F
when     = 'zsh ~/dotfiles/zsh/node-version.zsh'

[custom.rbenv]
disabled = false
style    = 'fg:white-2-fg'
format   = "[ ([$symbol](red-fg)$output) ]($style)"
command  = 'zsh ~/dotfiles/zsh/ruby-version.zsh'
symbol   = ' ' # https://unicode-explorer.com/c/202F
when     = 'zsh ~/dotfiles/zsh/ruby-version.zsh'

[directory]
disabled          = false
style             = 'bg:power-2-bg fg:power-2-fg'
format            = '[  $path]($style)[$read_only]($read_only_style)'
home_symbol       = '~' # '󰣘'
truncate_to_repo  = false
truncation_length = 4
truncation_symbol = '…/'

[fill]
disabled = true
symbol   = ' '

[git_branch]
style  = 'bg:power-3-bg fg:power-3-fg'
format = '[ $symbol $branch(:$remote_branch)]($style)'
symbol = ''

[git_commit]
disabled      = false
style         = 'bg:power-4-bg fg:power-4-fg'
format        = '[  $hash$tag]($style)'
only_detached = false
tag_disabled  = false
tag_symbol    = '  '

[git_metrics]
disabled      = false
format        = '([[](green-fg)+$added ]($added_style))([ -$deleted[](red-fg)]($deleted_style))'
added_style   = 'bold bg:green-fg fg:green-bg'
deleted_style = 'bold bg:red-fg fg:red-bg'

[git_state]
format = '\([$state($progress_current/$progress_total)]($style)\) '

[git_status]
style      = ''
format     = '[ $ahead_behind$staged$untracked$renamed$modified$deleted$conflicted$stashed]($style)'
ahead      = '[↑${count} ](magenta-fg)'
behind     = '[↓${count} ](blue-fg)'
conflicted = '[󰳤 ${count} ](red-fg)'
deleted    = '[󰛲 ${count} ](red-fg)'
diverged   = '[[↑${ahead_count}](magenta-fg) [↓${behind_count}](blue-fg) ]($style)'
modified   = '[󱗝 ${count} ](yellow-fg)'
renamed    = '[󰏭 ${count} ](yellow-fg)'
staged     = '[ ${count} ](blue-fg)'
stashed    = '[󰰡 ${count} ](magenta-fg)'
untracked  = '[󰜄 ${count} ](green-fg)'

[line_break]
disabled = false

[time]
disabled        = false
style           = 'bg:power-1-bg fg:white-fg'
format          = '[  $time]($style)'
time_format     = '%R'
utc_time_offset = 'local'

# Choose second color from the left
# https://colorkit.io/shades-tints/#F7768E-9
[palettes.tokyo-night-neon]
white-fg      = '#C0CAF5'
white-2-fg    = '#A9B1D6'
black-fg      = '#1A1B26'
black-2-fg    = '#414868'
#
red-fg        = '#F7768E'
red-bg        = '#310E15'
green-fg      = '#73DACA'
green-bg      = '#0E2533'
yellow-fg     = '#E0AF68'
yellow-bg     = '#2C200f'
blue-fg       = '#7AA2F7'
blue-bg       = '#0E1A31'
magenta-fg    = '#BB9AF7'
magenta-bg    = '#31244A'
cyan-fg       = '#7DCFFF'
cyan-bg       = '#0E2533'
#
power-1-fg    = '#C0CAF5'
power-1-bg    = '#1A1B26'
power-2-fg    = '#73DACA'
power-2-bg    = '#152B28'
power-3-fg    = '#7DCFFF'
power-3-bg    = '#0E2533'
power-4-fg    = '#BB9AF7'
power-4-bg    = '#1D1331'
